export { default as BootScene } from './Boot'
export { default as GameScene } from './Game'
export { default as MenuScene } from './Menu'
export { default as LevelSelectScene } from './LevelSelect'
export { default as CreditsScene } from './Credits'
